# Generated by Django 3.2.9 on 2021-12-11 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ste', '0001_initial'),
        ('me', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_Demmand', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('Description', models.TextField(null=True)),
                ('create_at', models.DateField(auto_now_add=True, null=True)),
                ('photo', models.ImageField(upload_to='')),
                ('count_Dommand', models.IntegerField(null=True)),
                ('ste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ste.societe')),
                ('user', models.ManyToManyField(through='post.MePost', to='me.ME')),
            ],
        ),
        migrations.AddField(
            model_name='mepost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post'),
        ),
        migrations.AddField(
            model_name='mepost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='me.me'),
        ),
    ]
