# Generated by Django 4.0.2 on 2022-02-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='expiration',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
