# Generated by Django 3.2.9 on 2021-12-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_ste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='count_Dommand',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
