# Generated by Django 3.2.9 on 2021-12-25 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_count_dommand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['create_at']},
        ),
    ]
