# Generated by Django 3.2.9 on 2022-01-29 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ste', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_Payment', models.DateTimeField(auto_now_add=True)),
                ('method_Payment', models.EmailField(max_length=254)),
                ('ste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ste.societe')),
            ],
        ),
    ]
