# Generated by Django 3.2.9 on 2021-12-11 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ste', '0001_initial'),
        ('me', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Libell', models.CharField(choices=[('in progress', 'in progress'), ('out the order', 'out the order'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], max_length=30)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('prix', models.FloatField()),
                ('VL', models.BooleanField()),
                ('Busy', models.BooleanField(default=False, null=True)),
                ('photo', models.ImageField(upload_to='')),
                ('Categorie', models.CharField(choices=[('in progress', 'in progress'), ('out the order', 'out the order'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], max_length=30)),
                ('me', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='me.me')),
                ('ste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ste.societe')),
            ],
        ),
    ]
