# Generated by Django 3.2.9 on 2022-01-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['email']},
        ),
        migrations.RemoveField(
            model_name='message',
            name='username',
        ),
        migrations.AddField(
            model_name='message',
            name='first_name',
            field=models.CharField(default='Client', max_length=50),
        ),
        migrations.AddField(
            model_name='message',
            name='last_name',
            field=models.CharField(default='Client', max_length=50),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(default='Client', max_length=2000),
        ),
    ]
