# Generated by Django 3.2.9 on 2021-12-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ste', '0002_societe_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societe',
            name='name_STE',
            field=models.CharField(max_length=50, unique=True, verbose_name='name_STE'),
        ),
    ]
