# Generated by Django 3.2.9 on 2021-12-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ste', '0003_alter_societe_name_ste'),
    ]

    operations = [
        migrations.AddField(
            model_name='societe',
            name='active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
