# Generated by Django 3.2.9 on 2021-12-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ste', '0004_societe_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societe',
            name='name_STE',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
