# Generated by Django 3.2.9 on 2022-01-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ste', '0005_alter_societe_name_ste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societe',
            name='photo',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to=''),
        ),
    ]
