# Generated by Django 3.2.9 on 2022-01-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0002_auto_20211218_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='me',
            name='photo',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to=''),
        ),
    ]
